### ISSUE TITLE
兄弟的意思是原接口还能抢吗？我抓包看 有接口是变动了

### ISSUE THREAD

**Issue by Pluto1219** [yddeng/seckill#1]

**Comment by yddeng** [comment]
目前我也还在调试，年前我看的接口是这些

**Comment by Pluto1219** [comment]
确定变了 好兄弟



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ydd <notifications@github.com&gt;
发送时间: 2021年2月22日 11:49
收件人: yddeng/seckill <seckill@noreply.github.com&gt;
抄送: Pluto1219 <1990218899@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yddeng/seckill] 兄弟的意思是原接口还能抢吗？我抓包看 有接口是变动了 (#1)

**Comment by yddeng** [comment]
是抓包抢茅台的吗，京东茅台和其他秒杀商品流程不一样

**Comment by Pluto1219** [comment]
茅台的包 好兄弟可以聊一下 微 jununj





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ydd <notifications@github.com&gt;
发送时间: 2021年2月22日 11:59
收件人: yddeng/seckill <seckill@noreply.github.com&gt;
抄送: Pluto1219 <1990218899@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yddeng/seckill] 兄弟的意思是原接口还能抢吗？我抓包看 有接口是变动了 (#1)
